spring.application.name=campaign-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/campaign_service
spring.datasource.username=aidflow
spring.datasource.password=aidflow

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
