spring.application.name=gateway-service
server.port=8080

identity-service.base-url=http://localhost:8081

spring.cloud.gateway.routes[0].id=identity-auth
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=campaign-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/campaigns/**
